### ISSUE TITLE
Migrate to Golang 1.20

### ISSUE THREAD

**Issue by eyal-mor** [Autodesk/shore#25]
## Summary

Update Packages and validate `Golang 1.20` compiles/tests the project
correctly

**Comment by dkirillov** [comment]
Depending on what we do - going `1.18 -> 1.19 -> 1.20` OR `1.18 -> 1.20` - PR #14 can be used as an example of what needs to change.

**Comment by dkirillov** [comment]
The PR to bump the version has been merged.

Closing this issue.
